<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Please enter a valid mobile number_l_e64f24</name>
   <tag></tag>
   <elementGuidId>e7aff872-8830-4c5f-a0a6-6ea3b3d299ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='login_iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login_iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#login_iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4bedae65-7f5e-427d-89cc-4e9e9db51650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_iframe</value>
      <webElementGuid>c9c618d0-5f35-4ec3-8f53-78231b0f9987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-component-iframe</value>
      <webElementGuid>b8f3777c-7814-4b89-9634-0db0d87cf97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mybillbook.in/app/login?source=iframe</value>
      <webElementGuid>7a1f1df5-611c-4ca2-8f90-d50d5dd88bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-43</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>838244ba-e002-45db-aaad-db77ab41171a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_iframe&quot;)</value>
      <webElementGuid>fedb3c86-cb70-4261-b7de-3942b65fc25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-45</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6dce5337-5906-48c5-9186-94b59e197eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-47</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6840c295-f127-4f28-a8c2-42d5f20c8661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='login_iframe']</value>
      <webElementGuid>d0920e4f-78bf-40c2-8889-245bc223fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_container_id']/iframe</value>
      <webElementGuid>1f3703ca-eed2-48b5-80b1-17543d324b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>2edbbd71-76bb-4390-a3d0-7967ca5a9d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'login_iframe' and @src = 'https://mybillbook.in/app/login?source=iframe']</value>
      <webElementGuid>94ad0ba2-6a78-4faa-a9a9-e949cffcac8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
