<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zimbabwe (263)_mobile-number</name>
   <tag></tag>
   <elementGuidId>c5e4f30d-0e4c-4937-ab34-3326713c81e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Mobile Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b470b664-1b90-44da-b5d4-df609cddb78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile-number</value>
      <webElementGuid>750d42ad-2178-412e-ad6e-466f55b27585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b24d67b-ad84-42fc-89a8-1787e6451ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>c688edc3-6d17-41e9-a5ca-bc4283c5d1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>64273399-7ef2-4a9b-968b-f63c8f2e02eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onlynumber</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4d7260b-348d-4a3a-a1e2-05cdbcb024fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f5f3e470-a0fd-4c24-bd59-108160b804e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-number&quot;)</value>
      <webElementGuid>271a5ec5-98df-4656-9c95-bb08baeffd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_GST Billing Software Free Download  Be_a4fa79/iframe_Please enter a valid mobile number_l_e64f24</value>
      <webElementGuid>87916874-84d4-4dc2-b029-9bfd7ac626d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile-number']</value>
      <webElementGuid>40c38a1c-ef77-49e3-9c73-77dbaca8ba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@flobiz/web-app']/app-root/div/div/app-login/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>144dc148-f2c7-44f6-8c35-f58c644be00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>808f19b5-873c-43d3-acdc-4661451157f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobile-number' and @type = 'text' and @placeholder = 'Mobile Number']</value>
      <webElementGuid>6cc5f7da-21ef-4beb-8f1d-dc4acfb3dc99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
