<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>ed12f875-1313-4985-a958-525d6abbc6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;showLogin(false); showLoginEvent('Login/Register', 'login',trackingEventAttributeType, 'login')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.header-btn.empty-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76a040a5-1f6f-4393-99e7-8a1fb6cf3d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-btn empty-button</value>
      <webElementGuid>447ea3b8-351e-496d-86bc-95a2f6aed579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showLogin(false); showLoginEvent('Login/Register', 'login',trackingEventAttributeType, 'login')</value>
      <webElementGuid>5ae5bb2c-1e2a-46d1-944f-1b79e92db2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Login
            </value>
      <webElementGuid>9e9411c2-85f0-4b65-8bf3-dbba3272b39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-section d-flex justify-content-space-between align-items-center&quot;]/div[@class=&quot;header-actions&quot;]/button[@class=&quot;header-btn empty-button&quot;]</value>
      <webElementGuid>f06d8956-1ac3-472e-b39f-12745cc00951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;showLogin(false); showLoginEvent('Login/Register', 'login',trackingEventAttributeType, 'login')&quot;]</value>
      <webElementGuid>d956f75c-742a-4d81-a94f-3feb1d5a000b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/div[3]/button</value>
      <webElementGuid>75dddf06-556d-4694-a06f-57b4bf8f2960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Account'])[1]/following::button[1]</value>
      <webElementGuid>076d7a19-7b4e-484f-8aa7-f8fcc4183294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talk to Sales'])[1]/following::button[2]</value>
      <webElementGuid>4ace4764-8d79-4ea8-baaa-2781fd61969a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Free Demo'])[1]/preceding::button[1]</value>
      <webElementGuid>b51e914d-0b4d-4aa8-8bdd-558aecce358a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Free Billing'])[1]/preceding::button[2]</value>
      <webElementGuid>8e784c50-02f7-415a-b5c3-99b4f752e212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>270da69c-1b54-4c08-a579-e948e21e3782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>11c8fc8c-63f5-4a37-98e7-650eefce2eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
              Login
            ' or . = '
              Login
            ')]</value>
      <webElementGuid>1948dc68-c459-48f9-8cf7-47366e0c08f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
